// release.config.js

/**
 * semantic-release configuration.
 *
 * This is a private Next.js app (deployed via Vercel), not an npm package, so
 * we configure semantic-release to:
 *   - analyze conventional commits to determine the next version
 *   - update package.json's `version` field (via @semantic-release/npm with
 *     `npmPublish: false`, since `"private": true` would block publish anyway)
 *   - regenerate CHANGELOG.md
 *   - commit those updates back to `main` with a `[skip ci]` marker so the
 *     release commit doesn't retrigger the workflow
 *   - create a GitHub Release with auto-generated notes
 *
 * Configured branch: `main` only.
 *
 * Required workflow secrets/permissions:
 *   - GITHUB_TOKEN with `contents: write`, `issues: write`, `pull-requests: write`
 *
 * Local dry-run:
 *   npx semantic-release --dry-run --no-ci
 */

const preset = "conventionalcommits";

/** @type {import('semantic-release').GlobalConfig} */
module.exports = {
  branches: ["main"],
  plugins: [
    [
      "@semantic-release/commit-analyzer",
      {
        preset,
        releaseRules: [
          { type: "docs", release: "patch" },
          { type: "refactor", release: "patch" },
          { type: "perf", release: "patch" },
          { type: "style", release: false },
          { type: "test", release: false },
          { type: "build", release: false },
          { type: "ci", release: false },
          { type: "chore", release: false },
        ],
      },
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        preset,
        presetConfig: {
          types: [
            { type: "feat", section: "Features" },
            { type: "fix", section: "Bug Fixes" },
            { type: "perf", section: "Performance" },
            { type: "refactor", section: "Refactors" },
            { type: "docs", section: "Documentation" },
            { type: "build", section: "Build", hidden: true },
            { type: "ci", section: "CI", hidden: true },
            { type: "chore", section: "Chores", hidden: true },
            { type: "style", section: "Style", hidden: true },
            { type: "test", section: "Tests", hidden: true },
          ],
        },
      },
    ],
    [
      "@semantic-release/changelog",
      {
        changelogFile: "CHANGELOG.md",
        changelogTitle:
          "# Changelog\n\nAll notable changes to this project are documented here. " +
          "This file is generated by [semantic-release](https://github.com/semantic-release/semantic-release) " +
          "from [Conventional Commits](https://www.conventionalcommits.org/).",
      },
    ],
    [
      "@semantic-release/npm",
      {
        npmPublish: false,
      },
    ],
    [
      "@semantic-release/git",
      {
        assets: ["CHANGELOG.md", "package.json", "package-lock.json"],
        message:
          "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
      },
    ],
    [
      "@semantic-release/github",
      {
        successComment: false,
        failComment: false,
        releasedLabels: false,
      },
    ],
  ],
};
