"use client";
import Image from "next/image";
import { motion } from "framer-motion";
import { useState } from 'react';
import imageData from "../../public/image_data_summary.json";
import Link from "next/link";
// imageData is an object keyed by filename-stem; convert to an array and attach a public src.
const images = Object.values(imageData).map((it) => ({
  ...it,
  // files are saved as e.g. "1.jpg" in public/images — serve from /images/<file>
  src: `/images/${it.file}`,
  // thumbnail path (generated by generate_thumbs.py) lives in public/images_small
  // generator outputs WebP by default, so use .webp extension for thumbnails
  thumbSrc: `/images_small/${it.file.replace(/\.[^.]+$/, ".webp")}`,
}));

// sort images by mean_hue (ascending). You can flip to descending by reversing the compare.
const imagesSortedByMeanRGB = [...images].sort((a, b) => a.mean_hue - b.mean_hue);

const talks = [
  { title: 'UPLB DSG x UPRHS CodeIT Workshop Day 1 - What is Data Science?', src: '/talks/talk1.jpg' },
  { title: 'UPLB DSG x UPRHS CodeIT Workshop Day 2 - Storytelling with Data', src: '/talks/talk2.jpg' },
  { title: 'NextStep Hacks 2025 - Winning by Talking', src: '/talks/talk3.jpg' },
  { title: 'JPCS - QCU Logic Unlocked Day 1 - Machine Learning with Python', src: '/talks/talk4.jpg' },
  { title: "UPLB DSG Applicants' Workshop - Data Storytelling with Canva", src: '/talks/talk5.jpg' },
  { title: 'Data Engineering Pilipinas AI Study Group - AI Use Cases That Actually Matter', src: '/talks/talk6.jpg' },
  { title: '(upcoming) DLSU ECES - Agile Edge: Swift Project Workflows', src: '/talks/talk7.gif' },
];

const projects = [
  {
    title: 'HearthCraft',
    src: '/projects/project1.jpg',
    description: 'At 13 years old, I decided to take my deep enjoyment of Minecraft, learn to set up a Minecraft server, worked with both managed and bare-metal servers, set up Java plugins and Docker instances, and created a multiplayer experience that served as a safe space for 10,000+ over the span of 6+ years.',
  },
  {
    title: 'Atlas Of My Skies',
    src: '/projects/project2.jpg',
    description: 'Telling the story of the skies.',
  },
  {
    title: 'BARLO: Bayani Alert and Response for Local Operations',
    src: '/projects/project3.jpg',
    description: "Predict a storms economic impact from typhoon forecast data. Get insights on how to pre-emptively place logistics.",
  },
  {
    title: 'Pharmadash',
    src: '/projects/project4.jpg',
    description: 'A hackathon project for efficient pharmaceutical inventory management and distribution.',
  },
  {
    title: 'Punnett Square Visualizer',
    src: '/projects/project5.jpg',
    description: 'An interactive tool to visualize genetic crosses. Used in tutorials for science high school students',
  }
];
  const mediaItems = [
    { title: 'Sunset Boulevard', src: '/media/media1.jpg', description: 'Photography · 35mm film' },
    { title: 'City Geometry', src: '/media/media2.jpg', description: 'Photography · urban lines' },
    { title: 'Album Art – Drift', src: '/media/media3.jpg', description: 'Design · cover art' },
    { title: 'Poster – HackFest', src: '/media/media4.jpg', description: 'Design · event poster' },
    { title: 'Short Reel – Rain', src: '/media/media5.jpg', description: 'Media · 30s color study' },
    { title: 'Portrait Series', src: '/media/media6.jpg', description: 'Photography · natural light' },
    { title: 'Minimal UI Kit', src: '/media/media7.jpg', description: 'Design · Figma components' },
    { title: 'Night Walks', src: '/media/media8.jpg', description: 'Photography · low-light' },
    { title: 'Logo Study – Atlas', src: '/media/media9.jpg', description: 'Design · mark exploration' },
  ];
  // const orgs = [
  //   { title: 'UPLB Data Science Guild', src: '/orgs/org1.jpg', description: 'Resource Speaker · 2024–2025' },
  //   { title: 'Data Engineering Pilipinas', src: '/orgs/org2.jpg', description: 'Community Volunteer' },
  //   { title: 'A', src: '/orgs/org4.jpg', description: 'Mentor/Judge · 2025' },
  //   { title: 'DLSU ECES', src: '/orgs/org5.jpg', description: 'Speaker · 2025' },
  //   { title: 'UPRHS', src: '/orgs/org6.jpg', description: 'Workshop · 2024' },
  //   { title: 'Open Source', src: '/orgs/org7.jpg', description: 'Contributor · ongoing' },
  //   { title: 'Local NGOs', src: '/orgs/org8.jpg', description: 'Volunteer · ongoing' },
  //   { title: 'Startup Collabs', src: '/orgs/org9.jpg', description: 'Engineer · various' },
  // ];


function Thumb({ image }) {
  const [src, setSrc] = useState(image.thumbSrc);
  const [triedFallback, setTriedFallback] = useState(false);

  const handleError = () => {
    // If the thumbnail failed, try the original full-size image as a fallback.
    if (!triedFallback && image.src) {
      setTriedFallback(true);
      setSrc(image.src);
    }
  };

  // Use the image's mean_rgb as a placeholder background while loading.
  const bg = image.mean_rgb
    ? `rgb(${Math.round(image.mean_rgb[0])}, ${Math.round(image.mean_rgb[1])}, ${Math.round(image.mean_rgb[2])})`
    : "#111";

  return (
    <div style={{ position: "relative", width: "100%", paddingTop: "100%", background: bg, overflow: 'hidden' }}>
      <Image
        src={src}
        alt={image.file || "image"}
        onError={handleError}
        // Render as a square thumbnail. Using fixed size keeps layout stable.
        width={320}
        height={320}
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          filter: "sepia(0.5) blur(1px)",
        }}
        loading="lazy"
      />
    </div>
  );
}

export default function Home() {
  const [overlayMinimized, setOverlayMinimized] = useState(false);

  return (
    <div className="absolute inset-0 h-screen bg-black w-full overflow-hidden">
      <motion.div
        className="relative grid w-full mx-auto"
        style={{ zIndex: 0, gridTemplateColumns: "repeat(auto-fit, minmax(64px, 1fr))", gap: '0.5rem' }}
      >
        {imagesSortedByMeanRGB.map((image) => (
          <motion.div
            key={image.src}
            whileHover={{ scale: 1.05, zIndex: 10, filter: "brightness(1.08)", boxShadow: "0 20px 30px rgba(0,0,0,0.35)" }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            <Thumb key={image.src} image={image} />
          </motion.div>
        ))}
        {imagesSortedByMeanRGB.map((image) => (
          <motion.div
            key={image.src}
            whileHover={{ filter: "sepia(0) blur(0)", scale: 1.05, zIndex: 10, filter: "brightness(1.08)", boxShadow: "0 20px 30px rgba(0,0,0,0.35)" }}
            transition={{ type: "spring", stiffness: 300, damping: 20 }}
          >
            <Thumb key={image.src} image={image} />
          </motion.div>
        ))}
      </motion.div>
      {/* Centered test overlay: wrapper is full-screen fixed flex to center its child. 
          The inner box is pointer-events-auto so it receives clicks while the wrapper lets events pass through. */}
      <div className="fixed inset-0 flex items-center justify-center pointer-events-none" style={{ zIndex: 50 }}>
        {/* minimize / expand button (always visible) */}
        <button
          onClick={() => setOverlayMinimized((v) => !v)}
          className="pointer-events-auto absolute top-4 right-4 bg-gray-700/80 text-white p-2 rounded-md hover:bg-gray-600"
          aria-label={overlayMinimized ? 'Expand overlay' : 'Minimize overlay'}
        >
          {overlayMinimized ? '+' : '-'}
        </button>

        {!overlayMinimized && (
          <div className="pointer-events-auto bg-gray-800/70 text-white p-4 rounded backdrop-blur-sm max-h-10/12 max-w-11/12 w-2xl overflow-y-auto no-scrollbar">
            <div className="flex flex-col items-center">
              <div className="flex flex-row gap-5 items-center">
                <div className="flex flex-col gap-2 items-center">
                  <h1 className="font-sans text-7xl font-black text-white text-center">Stimmie</h1>
                  <div className="flex flex-row gap-2 justify-center">
                    <Link href="https://www.linkedin.com/in/stimmie">
                      <Image src="/logos/linkedin.png" alt="LinkedIn Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://www.instagram.com/friedicecrm">
                      <Image src="/logos/instagram.png" alt="Instagramm Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://www.github.com/smmariquit">
                      <Image src="/logos/github.png" alt="GitHub Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://medium.com/@semariquit">
                      <Image src="/logos/Medium.png" alt="Medium Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    {/* Additional logos */}
                    <Link href="https://myanimelist.net/" title="MyAnimeList">
                      <Image src="/logos/myanimelist.png" alt="MyAnimeList Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://pizza-and-friends.webflow.io" title="Pizza and Friends">
                      <Image src="/logos/pizza.png" alt="Pizza Icon" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="http://letterboxd.com/stimmieuwu" title="Letterboxd">
                      <Image src="/logos/letterboxd.png" alt="Letterboxd Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://goodreads.com/stimmie" title="Goodreads">
                      <Image src="/logos/goodreads.png" alt="Goodreads Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://docs.google.com/document/d/1nO2-vsOKjl4C_AngSSqc-knkUZvjJhe700unYZzcYsg/edit?usp=sharing" title="Hackathons">
                      <Image src="/logos/hackathon.png" alt="Hackathon Icon" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://docs.google.com/document/d/1nO2-vsOKjl4C_AngSSqc-knkUZvjJhe700unYZzcYsg/edit?usp=sharing" title="Freshie">
                      <Image src="/logos/freshie.png" alt="Freshie Icon" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://open.kattis.com/users/simonee" title="Kattis">
                      <Image src="/logos/kattis.png" alt="Kattis Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://open.spotify.com/user/opzo90f4votlfqmg9rl94qrra?si=538e1f5748424274" title="Spotify">
                      <Image src="/logos/spotify.png" alt="Spotify Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://www.last.fm/user/mistakenpog" title="Last.fm">
                      <Image src="/logos/lastfm.png" alt="Last.fm Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://leetcode.com/u/stimmers/" title="LeetCode">
                      <Image src="/logos/leetcode.png" alt="LeetCode Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="https://www.strava.com/athletes/129023200" title="Strava">
                      <Image src="/logos/strava.png" alt="Strava Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                    <Link href="mailto:semariquit@gmail.com">
                      <Image src="/logos/email.png" alt="Email Logo" width="24" height="24" className="rounded-1xl" />
                    </Link>
                  </div>
                </div>
              </div>
              <div>
                <div className="flex-1 min-w-0 max-w-4xl mt-5">
                  <h2 className="font-bold text-2xl">Hi!</h2>
                  <p className="text-white wrap-break-word">I’m a software engineer with a lifelong passion for technology. What began with hosting Minecraft servers and experimenting with cloud computers has evolved into building modern tech solutions for startups, organizations, and businesses.</p>
                  <br />
                  <p className="text-white wrap-break-word">Outside of my career, I'm also an avid book reader, sometimes writer, volunteer, resource speaker, mentor, runner, gym-goer, and someone who cares deeply about public service :)</p>
                </div>
                <div className="flex-1 min-w-0 max-w-4xl mt-5">
                  <h2 className="font-bold text-2xl"></h2>
                </div>
                <div className="flex-1 min-w-0 max-w-4xl mt-5">
                  <h2 className="font-bold text-2xl">Talks</h2>
                  <p className="text-white">Sometimes, I get invited to talks!</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mt-3">
                    {talks.slice(0, 9).map((t, idx) => (
                      <div key={idx} className="flex flex-col items-center bg-white/5 p-2 rounded">
                        <Image src={t.src} alt={t.title} width={320} height={180} className="object-cover rounded" />
                        <p className="text-sm text-white mt-2 text-center">{t.title}</p>
                      </div>
                    ))}
                  </div>
                </div>
                {/* Projects section */}
                <div className="flex-1 min-w-0 max-w-4xl mt-8 w-full">
                  <h2 className="font-bold text-2xl">Projects</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mt-3">
                    {projects.map((p, idx) => (
                      <div key={idx} className="flex flex-col bg-white/5 p-3 rounded">
                        <Image src={p.src} alt={p.title} width={320} height={180} className="object-cover rounded" />
                        <h3 className="text-white font-semibold mt-2">{p.title}</h3>
                        <p className="text-sm text-white/80 mt-1">{p.description}</p>
                      </div>
                    ))}
                  </div>
                </div>
                {/* Media section */}
                {/* <div className="flex-1 min-w-0 max-w-4xl mt-8 w-full">
                  <h2 className="font-bold text-2xl">Photography, Design, and Media</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mt-3">
                    {mediaItems.map((m, idx) => (
                      <div key={idx} className="flex flex-col bg-white/5 p-3 rounded">
                        <Image src={m.src} alt={m.title} width={320} height={180} className="object-cover rounded" />
                        <h3 className="text-white font-semibold mt-2">{m.title}</h3>
                        {m.description && <p className="text-sm text-white/80 mt-1">{m.description}</p>}
                      </div>
                    ))}
                  </div>
                </div> */}
                {/* Organizations and Past Experience */}
                {/* <div className="flex-1 min-w-0 max-w-4xl mt-8 w-full">
                  <h2 className="font-bold text-2xl">Organizations and Past Experience</h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mt-3">
                    {orgs.map((o, idx) => (
                      <div key={idx} className="flex flex-col bg-white/5 p-3 rounded">
                        <Image src={o.src} alt={o.title} width={320} height={180} className="object-cover rounded" />
                        <h3 className="text-white font-semibold mt-2">{o.title}</h3>
                        <p className="text-sm text-white/80 mt-1">{o.description}</p>
                      </div>
                    ))}
                  </div>
                </div> */}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
