#!/usr/bin/env node
/**
 * Merge harvest JSON blocks from research/opportunities/responses/*.md
 * into src/data/opportunity-board-items.js
 *
 *   node scripts/merge-harvest.mjs research/opportunities/responses/2026-06-24-harvest.md
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { slugifyOpportunityTitle } from "../src/data/opportunities.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const harvestArg = process.argv
  .slice(2)
  .find((arg) => !arg.startsWith("--"));
const harvestPath =
  harvestArg ??
  path.join(root, "research/opportunities/responses/2026-06-24-harvest.md");
const outPath = path.join(root, "src/data/opportunity-board-items.js");
const baselinePath = path.join(root, "src/data/opportunity-board-items.js");

function normUrl(url) {
  try {
    const parsed = new URL(url);
    const path = `${parsed.pathname}${parsed.search}`.replace(/\/$/, "");
    return `${parsed.hostname}${path}`.toLowerCase();
  } catch {
    return url.toLowerCase();
  }
}

function harvestToItem(entry) {
  const item = {
    title: entry.title,
    type: entry.type,
    url: entry.url,
    org: entry.org,
    location: entry.location,
    blurb: entry.blurb,
  };

  if (entry.dates?.length) {
    item.dates = entry.dates;
  }

  if (entry.image_url) {
    item.imageUrl = entry.image_url;
  }

  return item;
}

function parseHarvestMarkdown(markdown) {
  return [...markdown.matchAll(/```json\n([\s\S]*?)```/g)].map((match) =>
    JSON.parse(match[1]),
  );
}

function mergeItems(existing, harvested) {
  const seenUrls = new Set(existing.map((item) => normUrl(item.url)));
  const seenTitles = new Set(
    existing.map((item) => slugifyOpportunityTitle(item.title)),
  );

  const merged = [...existing];
  let added = 0;

  for (const entry of harvested) {
    const item = harvestToItem(entry);
    const urlKey = normUrl(item.url);
    const titleKey = slugifyOpportunityTitle(item.title);

    if (seenUrls.has(urlKey) || seenTitles.has(titleKey)) {
      continue;
    }

    seenUrls.add(urlKey);
    seenTitles.add(titleKey);
    merged.push(item);
    added += 1;
  }

  return { merged, added };
}

function formatItem(item, indent = "    ") {
  const lines = [`${indent}{`];
  lines.push(`${indent}  title: ${JSON.stringify(item.title)},`);
  lines.push(`${indent}  type: ${JSON.stringify(item.type)},`);
  lines.push(`${indent}  url: ${JSON.stringify(item.url)},`);

  if (item.imageUrl) {
    lines.push(`${indent}  imageUrl: ${JSON.stringify(item.imageUrl)},`);
  }
  if (item.image) {
    lines.push(`${indent}  image: ${JSON.stringify(item.image)},`);
  }
  if (item.imageAlt) {
    lines.push(`${indent}  imageAlt: ${JSON.stringify(item.imageAlt)},`);
  }

  lines.push(`${indent}  org: ${JSON.stringify(item.org)},`);
  lines.push(`${indent}  location: ${JSON.stringify(item.location)},`);

  if (item.dates?.length) {
    lines.push(`${indent}  dates: ${JSON.stringify(item.dates, null, 2).replace(/\n/g, `\n${indent}  `)},`);
  }

  lines.push(`${indent}  blurb: ${JSON.stringify(item.blurb)},`);
  lines.push(`${indent}},`);
  return lines.join("\n");
}

function writeItemsFile(items, sourceFile) {
  const body = items.map((item) => formatItem(item)).join("\n");
  const content = `// Generated by scripts/merge-harvest.mjs — do not edit by hand.
// Source: ${path.relative(root, sourceFile)}
// Regenerate: node scripts/merge-harvest.mjs

export const opportunityBoardItems = [
${body}
];
`;

  fs.writeFileSync(outPath, content);
}

const markdown = fs.readFileSync(harvestPath, "utf8");
const harvested = parseHarvestMarkdown(markdown);

async function loadExistingItems() {
  const baselineArg = process.argv.find((arg) => arg.startsWith("--baseline="));
  const baselineCount = baselineArg
    ? Number(baselineArg.split("=")[1])
    : null;

  if (baselineCount && fs.existsSync(baselinePath)) {
    const { opportunityBoardItems } = await import(
      `file://${baselinePath}?t=${Date.now()}`
    );
    return opportunityBoardItems.slice(0, baselineCount);
  }

  const { opportunitiesBoard } = await import(
    `file://${path.join(root, "src/data/opportunities.js")}?t=${Date.now()}`
  );
  return opportunitiesBoard.items;
}

const existing = await loadExistingItems();
const { merged, added } = mergeItems(existing, harvested);

writeItemsFile(merged, harvestPath);

console.log(
  `Merged ${added} new items (${harvested.length} in harvest, ${existing.length} existing → ${merged.length} total)`,
);
console.log(`Wrote ${path.relative(root, outPath)}`);
